# Этап 1: Сборка
FROM node:18-alpine AS builder

# Устанавливаем pnpm
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

# На этом этапе Vite увидит переменные из ENV
RUN pnpm build

# Этап 2: Статический сервер
FROM node:18-alpine

RUN npm install -g serve

WORKDIR /app
COPY --from=builder /app/dist .

EXPOSE 3000
CMD ["serve", "-s", ".", "-l", "3000"]
