version: "3.9"

services:
  frontend:
    container_name: vite-react-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
   
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
